// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the engine's current [`AppSettings`]. */
	getCurrentSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_current_settings")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,color_filter:({...v.data.color_filter,color_matrix:v.data.color_filter.color_matrix==null?v.data.color_filter.color_matrix:v.data.color_filter.color_matrix.map(i=>i)})}) } : v) as typeof v)),
	/**
	 *  Returns the latest [`FrameTimingSummary`] (zeroed/last-known before the loop
	 *  runs; never errors).
	 */
	getFrameTimings: () => typedError<FrameTimingSummary, string>(__TAURI_INVOKE("get_frame_timings")),
	/**
	 *  Sets the zoom level (clamped to `[1.5, 20]`; `NaN` rejected) and wakes the
	 *  loop.
	 */
	setZoomLevel: (level: number) => typedError<null, string>(__TAURI_INVOKE("set_zoom_level", { level })),
	/**  Sets the magnification mode and wakes the loop. */
	setMagnificationMode: (mode: MagnificationMode) => typedError<null, string>(__TAURI_INVOKE("set_magnification_mode", { mode })),
	/**  Toggles magnification, wakes the loop, and returns the new active state. */
	toggleMagnification: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_magnification")),
	/**  Persists the current settings to `config.toml`. */
	saveSettings: () => typedError<null, string>(__TAURI_INVOKE("save_settings")),
	/**
	 *  Resets settings to defaults, applies them to the live state, and returns the
	 *  defaults.
	 */
	resetSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("reset_settings")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,color_filter:({...v.data.color_filter,color_matrix:v.data.color_filter.color_matrix==null?v.data.color_filter.color_matrix:v.data.color_filter.color_matrix.map(i=>i)})}) } : v) as typeof v)),
};

/** Events */
export const events = {
	modeChanged: makeEvent<ModeChangedEvent>("mode_changed"),
	zoomChanged: makeEvent<ZoomChangedEvent>("zoom_changed"),
};

/* Types */
/**
 *  Root application settings schema.
 * 
 *  This struct represents all user-configurable settings. It is
 *  serialized to `config.toml` for persistence and to JSON for IPC.
 *  The TypeScript `AppSettings` Zod schema (doc-05 Section 3.2)
 *  mirrors this struct field-for-field.
 */
export type AppSettings = {
	/**  Magnification display settings. */
	magnification: MagnificationSettings,
	/**  Color filter settings. */
	color_filter: ColorFilterConfig,
	/**  Cursor enhancement settings. */
	cursor: CursorConfig,
	/**  Speech / TTS settings. */
	speech: SpeechSettings,
	/**  Keyboard shortcut bindings (action -> binding or null). */
	keybindings: Partial<{ [key in HotkeyAction]: KeyBinding | null }>,
	/**  Whether Luminos starts automatically on login. */
	start_on_login: boolean,
	/**  Whether closing the control panel minimizes to tray. */
	minimize_to_tray: boolean,
	/**  Whether the control panel is shown on application start. */
	show_panel_on_start: boolean,
};

/**  Color filter configuration. */
export type ColorFilterConfig = {
	/**  Active filter type. */
	filter_type: ColorFilterType,
	/**  Brightness adjustment (-1.0 to 1.0). */
	brightness: number,
	/**  Contrast multiplier (0.0 to 3.0). */
	contrast: number,
	/**
	 *  Custom 4x4 color matrix (row-major, 16 elements).
	 *  Present only when `filter_type` is `Custom`.
	 */
	color_matrix: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number] | null,
};

/**  Color filter applied to the magnified view. */
export type ColorFilterType = 
/**  No color filter (passthrough). */
"None" | 
/**  Full color inversion. */
"Invert" | 
/**  Inversion that preserves image hues (inverts lightness only). */
"SmartInvert" | 
/**  Converts to grayscale. */
"Grayscale" | 
/**  High-contrast black/white with configurable threshold. */
"HighContrast" | 
/**  User-defined 4x4 color transformation matrix. */
"Custom";

/**  Cursor enhancement configuration. */
export type CursorConfig = {
	/**  Whether the cursor is enlarged in the magnified view. */
	enlarged_cursor: boolean,
	/**  Cursor scale factor (1.0 to 4.0). */
	cursor_scale: number,
	/**  Whether crosshairs are drawn at the cursor position. */
	crosshairs_enabled: boolean,
	/**  Crosshair line width in pixels (1-10). */
	crosshair_width: number,
	/**  Crosshair color as CSS hex string (e.g., "#ff0000"). */
	crosshair_color: string,
	/**  Whether a halo circle surrounds the cursor. */
	halo_enabled: boolean,
	/**  Halo radius in pixels (10-200). */
	halo_radius: number,
	/**  Halo color as CSS hex string. */
	halo_color: string,
};

/**  The edge of the screen where a docked overlay attaches. */
export type DockEdge = 
/**  Top edge of the screen. */
"Top" | 
/**  Bottom edge of the screen. */
"Bottom" | 
/**  Left edge of the screen. */
"Left" | 
/**  Right edge of the screen. */
"Right";

/**
 *  IPC-ready frame timing summary.
 * 
 *  Contains aggregate statistics suitable for transmission to the
 *  control panel via Tauri IPC (E04+). All time fields are in
 *  milliseconds.
 * 
 *  # Wire format (DC-5)
 * 
 *  This is the **one** IPC type renamed to `camelCase`: the JSON keys are
 *  `averageMs`, `p99Ms`, `minMs`, `maxMs`, `targetFps` (story 006's Zod schema
 *  and `tauri-specta` bindings depend on exactly these keys). All other IPC
 *  types (`AppSettings` + sub-structs) stay `snake_case`.
 */
export type FrameTimingSummary = {
	/**  Average frame time in milliseconds. */
	averageMs: number,
	/**  P99 frame time in milliseconds. */
	p99Ms: number,
	/**  Minimum frame time in milliseconds. */
	minMs: number,
	/**  Maximum frame time in milliseconds. */
	maxMs: number,
	/**  Target frame rate. */
	targetFps: number,
};

/**  GPU device preference. */
export type GpuPreference = 
/**  Integrated GPU (lower power, default). */
"LowPower" | 
/**  Discrete GPU (higher performance). */
"HighPerformance";

/**  Hotkey action identifiers. */
export type HotkeyAction = 
/**  Increase zoom level. */
"ZoomIn" | 
/**  Decrease zoom level. */
"ZoomOut" | 
/**  Reset zoom to default. */
"ZoomReset" | 
/**  Toggle magnification on/off. */
"ToggleMagnification" | 
/**  Cycle through magnification modes. */
"CycleMode" | 
/**  Read aloud what is visible on screen. */
"ReadWhatISee" | 
/**  Read aloud the current text selection. */
"ReadSelection" | 
/**  Stop any active speech. */
"StopSpeech" | 
/**  Visually locate the cursor. */
"FindCursor";

/**  Scaling interpolation algorithm. */
export type InterpolationMode = 
/**  Bilinear filtering (Phase 0 default). */
"Bilinear" | 
/**  Bicubic filtering (Phase 1+, higher quality). */
"Bicubic";

/**  A keyboard shortcut binding. */
export type KeyBinding = {
	/**  Key name (e.g., "Equal", "Minus", "F1"). */
	key: string,
	/**  Modifier keys required. */
	modifiers: ModifierKey[],
};

/**  The shape of a lens-mode overlay. */
export type LensShape = 
/**  Rectangular lens boundary. */
"Rectangle" | 
/**  Elliptical lens boundary. */
"Ellipse";

/**  Screen magnification display mode. */
export type MagnificationMode = 
/**  Entire screen is magnified; overlay covers full display. */
"FullScreen" | 
/**  Magnified view docked to a screen edge. */
"Docked" | 
/**  Magnifying glass lens follows cursor. */
"Lens";

/**  Magnification-related settings. */
export type MagnificationSettings = {
	/**  Zoom level multiplier (1.5 to 20.0). */
	zoom_level: number,
	/**  Active magnification display mode. */
	mode: MagnificationMode,
	/**  What the viewport tracks. */
	tracking_mode: TrackingMode,
	/**  Docked mode: which screen edge (if docked). */
	docked_edge: DockEdge | null,
	/**  Docked mode: percentage of screen reserved (10-90). */
	docked_size_percent: number | null,
	/**  Lens mode: width in pixels. */
	lens_width: number | null,
	/**  Lens mode: height in pixels. */
	lens_height: number | null,
	/**  Lens mode: shape. */
	lens_shape: LensShape | null,
	/**  Target frames per second (15-144). */
	target_fps: number,
	/**  VSync/present strategy. */
	present_mode: PresentMode,
	/**  GPU selection preference. */
	gpu_preference: GpuPreference,
	/**  Scaling interpolation algorithm. */
	interpolation: InterpolationMode,
	/**  Smooth scrolling animation. */
	smooth_scrolling: boolean,
};

/**
 *  Emitted when the engine changes the magnification mode (hotkey-origin).
 *  Payload is the new mode. Wire name: `mode_changed`; generated TS object key:
 *  `events.modeChanged`.
 * 
 *  Phase-0 caveat: no Phase-0 hotkey changes mode yet (`dispatch_hotkey`'s
 *  `CycleMode` is a no-op, `luminos_core::hotkeys`), so this event has no
 *  engine-origin trigger in Phase 0 — the type/binding still must exist for the
 *  story-006 cross-language contract (AD-5 deviation, recorded in SUBTASKS).
 */
export type ModeChangedEvent = MagnificationMode;

/**  Kokoro ONNX model quantization variant. */
export type ModelVariant = 
/**  4-bit quantized model. */
"Q4" | 
/**  8-bit quantized model (~92MB). */
"Q8" | 
/**  16-bit floating point model. */
"Fp16" | 
/**  32-bit floating point model. */
"Fp32";

/**  Modifier key names for keybindings. */
export type ModifierKey = 
/**  Control key. */
"Ctrl" | 
/**  Shift key. */
"Shift" | 
/**  Alt key. */
"Alt" | 
/**  Super/Windows key (Linux/Windows). */
"Super" | 
/**  Meta key (macOS Command). */
"Meta";

/**  `VSync` / frame presentation strategy. */
export type PresentMode = 
/**  VSync-locked (Fifo), smooth, no tearing. */
"Quality" | 
/**  Mailbox, lowest input latency with GPU overhead. */
"LowLatency" | 
/**  Immediate, uncapped FPS for diagnostics. */
"Performance";

/**  Speech / TTS configuration. */
export type SpeechSettings = {
	/**  Whether TTS is enabled. */
	enabled: boolean,
	/**  Active voice identifier. */
	voice_id: string,
	/**  Speech rate multiplier (0.5 to 3.0). */
	speech_rate: number,
	/**  Speech volume (0.0 to 1.0). */
	speech_volume: number,
	/**  Kokoro quantization variant. */
	model_variant: ModelVariant,
};

/**  Which element the magnification viewport tracks. */
export type TrackingMode = 
/**  Viewport follows the mouse cursor. */
"Cursor" | 
/**  Viewport follows the keyboard focus element. */
"Focus" | 
/**  Viewport follows the text insertion caret. */
"TextCaret";

/**
 *  Emitted when the engine changes the zoom level (hotkey-origin). Payload is
 *  the new zoom multiplier. Wire name: `zoom_changed`; generated TS object key:
 *  `events.zoomChanged`.
 */
export type ZoomChangedEvent = number;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

