//! Audio output trait and associated types.
//!
//! Defines the [`AudioOutput`] trait for playing TTS audio samples,
//! along with [`AudioSample`] and [`AudioError`].

/// An audio sample buffer ready for playback.
#[derive(Debug, Clone)]
pub struct AudioSample {
    /// PCM audio data (f32 samples, mono or interleaved stereo).
    pub data: Vec<f32>,
    /// Sample rate in Hz (e.g., 24000 for Kokoro output).
    pub sample_rate: u32,
    /// Number of audio channels (1 = mono, 2 = stereo).
    pub channels: u16,
}

/// Errors that can occur during audio output.
#[derive(Debug, thiserror::Error)]
pub enum AudioError {
    /// No audio output device was found.
    #[error("no audio output device found")]
    NoDevice,

    /// The audio device failed to open or initialize.
    #[error("audio device error: {message}")]
    DeviceFailed {
        /// Description of the device failure.
        message: String,
    },

    /// Audio playback was interrupted by a device change or error.
    #[error("playback interrupted: {message}")]
    PlaybackInterrupted {
        /// Description of the interruption.
        message: String,
    },

    /// The sample format is unsupported by the output device.
    #[error("unsupported audio format: {message}")]
    UnsupportedFormat {
        /// Description of the unsupported format.
        message: String,
    },

    /// A platform-specific error occurred.
    #[error("platform audio error: {message}")]
    Platform {
        /// Description of the platform error.
        message: String,
    },
}

/// Audio output for TTS playback.
///
/// Wraps the `cpal` crate to provide a simplified interface for queuing
/// and playing audio samples generated by the TTS engine.
///
/// # Platform Backends
///
/// | Platform | cpal Backend |
/// |----------|-------------|
/// | Linux | ALSA or PulseAudio (cpal auto-selects) |
/// | macOS | CoreAudio |
/// | OpenBSD | sndio |
/// | Windows | WASAPI |
pub trait AudioOutput: Send + Sync {
    /// Plays the given audio sample.
    ///
    /// If `interrupt` is `true`, stops current playback first.
    fn play_audio(&self, sample: AudioSample, interrupt: bool) -> Result<(), AudioError>;

    /// Stops any audio currently playing.
    fn stop_audio(&self) -> Result<(), AudioError>;

    /// Sets the output volume. Linear scale 0.0 (silent) to 1.0 (full).
    fn set_volume(&self, volume: f32) -> Result<(), AudioError>;

    /// Returns the name of the default audio output device, if available.
    fn get_default_device_name(&self) -> Result<Option<String>, AudioError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn types_audio_sample_fields_and_derives() {
        let sample = AudioSample {
            data: vec![0.0, 0.5, -0.5, 1.0],
            sample_rate: 24000,
            channels: 1,
        };
        let debug = format!("{sample:?}");
        assert!(debug.contains("AudioSample"));
        let cloned = sample.clone();
        assert_eq!(cloned.sample_rate, 24000);
        assert_eq!(cloned.channels, 1);
        assert_eq!(cloned.data.len(), 4);
    }

    #[test]
    fn error_audio_error_display_no_device() {
        let err = AudioError::NoDevice;
        assert_eq!(err.to_string(), "no audio output device found");
    }

    #[test]
    fn error_audio_error_display_device_failed() {
        let err = AudioError::DeviceFailed {
            message: "ALSA init failed".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("audio device error"));
        assert!(msg.contains("ALSA init failed"));
    }

    #[test]
    fn error_audio_error_display_playback_interrupted() {
        let err = AudioError::PlaybackInterrupted {
            message: "device removed".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("playback interrupted"));
        assert!(msg.contains("device removed"));
    }

    #[test]
    fn error_audio_error_display_unsupported_format() {
        let err = AudioError::UnsupportedFormat {
            message: "48kHz not supported".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("unsupported audio format"));
        assert!(msg.contains("48kHz not supported"));
    }

    #[test]
    fn error_audio_error_display_platform() {
        let err = AudioError::Platform {
            message: "CoreAudio error".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("platform audio error"));
        assert!(msg.contains("CoreAudio error"));
    }
}
