//! Top-level application error hierarchy for Luminos.
//!
//! Defines [`LuminosError`], which unifies all subsystem errors from
//! `luminos-platform` into a single error type for the core engine.
//! Each subsystem error is automatically convertible via `From` impls
//! generated by `thiserror`'s `#[from]` attribute.

use luminos_platform::error::{
    AudioError, CaptureError, FocusError, InputError, TtsError, WindowError,
};

/// Top-level application error.
///
/// Each variant wraps a subsystem-specific error type. The `From` trait
/// is implemented for each subsystem error via `#[from]`, enabling `?`
/// propagation across subsystem boundaries without explicit matching.
#[derive(Debug, thiserror::Error)]
pub enum LuminosError {
    /// Screen capture subsystem error.
    #[error("screen capture: {0}")]
    Capture(#[from] CaptureError),

    /// Focus tracking subsystem error.
    #[error("focus tracking: {0}")]
    Focus(#[from] FocusError),

    /// Text-to-speech subsystem error.
    #[error("text-to-speech: {0}")]
    Tts(#[from] TtsError),

    /// Window management subsystem error.
    #[error("window management: {0}")]
    Window(#[from] WindowError),

    /// Input monitoring subsystem error.
    #[error("input monitoring: {0}")]
    Input(#[from] InputError),

    /// Audio output subsystem error.
    #[error("audio output: {0}")]
    Audio(#[from] AudioError),

    /// Configuration error (invalid settings, parse failure, I/O).
    #[error("configuration: {message}")]
    Config {
        /// Description of the configuration error.
        message: String,
    },

    /// Internal logic error (invariant violation, unexpected state).
    #[error("internal error: {message}")]
    Internal {
        /// Description of the internal error.
        message: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: propagates a subsystem error via `?` in a function returning
    /// `Result<(), LuminosError>`.
    fn propagate_capture() -> Result<(), LuminosError> {
        Err(CaptureError::PermissionDenied)?
    }

    fn propagate_focus() -> Result<(), LuminosError> {
        Err(FocusError::PermissionDenied)?
    }

    fn propagate_tts() -> Result<(), LuminosError> {
        Err(TtsError::VoiceNotFound("test".into()))?
    }

    fn propagate_window() -> Result<(), LuminosError> {
        Err(WindowError::CreationFailed {
            message: "test".into(),
        })?
    }

    fn propagate_input() -> Result<(), LuminosError> {
        Err(InputError::Unavailable {
            reason: "test".into(),
        })?
    }

    fn propagate_audio() -> Result<(), LuminosError> {
        Err(AudioError::NoDevice)?
    }

    #[test]
    fn luminos_error_from_capture_error() {
        let result = propagate_capture();
        assert!(matches!(result, Err(LuminosError::Capture(_))));
    }

    #[test]
    fn luminos_error_from_focus_error() {
        let result = propagate_focus();
        assert!(matches!(result, Err(LuminosError::Focus(_))));
    }

    #[test]
    fn luminos_error_from_tts_error() {
        let result = propagate_tts();
        assert!(matches!(result, Err(LuminosError::Tts(_))));
    }

    #[test]
    fn luminos_error_from_window_error() {
        let result = propagate_window();
        assert!(matches!(result, Err(LuminosError::Window(_))));
    }

    #[test]
    fn luminos_error_from_input_error() {
        let result = propagate_input();
        assert!(matches!(result, Err(LuminosError::Input(_))));
    }

    #[test]
    fn luminos_error_from_audio_error() {
        let result = propagate_audio();
        assert!(matches!(result, Err(LuminosError::Audio(_))));
    }

    #[test]
    fn luminos_error_display_capture() {
        let err = LuminosError::Capture(CaptureError::PermissionDenied);
        let msg = format!("{err}");
        assert!(
            msg.contains("screen capture"),
            "expected 'screen capture' in '{msg}'"
        );
    }

    #[test]
    fn luminos_error_display_config() {
        let err = LuminosError::Config {
            message: "bad value".into(),
        };
        let msg = format!("{err}");
        assert!(
            msg.contains("configuration"),
            "expected 'configuration' in '{msg}'"
        );
        assert!(msg.contains("bad value"), "expected 'bad value' in '{msg}'");
    }

    #[test]
    fn luminos_error_display_internal() {
        let err = LuminosError::Internal {
            message: "unexpected".into(),
        };
        let msg = format!("{err}");
        assert!(
            msg.contains("internal error"),
            "expected 'internal error' in '{msg}'"
        );
        assert!(
            msg.contains("unexpected"),
            "expected 'unexpected' in '{msg}'"
        );
    }
}
